# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

language: php

services:
  - mysql

addons:
  postgresql: "9.6"

jobs:
  include:
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: focal
      addons:
        postgresql: "12"
    - php: 8.0
      dist: focal
      addons:
        postgresql: "12"
    - php: 8.1
      dist: focal
      addons:
        postgresql: "12"
    - name: "PHP: 8.2"
      dist: jammy
      language: ruby
      addons:
        postgresql: "14"
      before_install:
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:ondrej/php
        - sudo apt update
        - sudo apt install php8.2 php8.2-pgsql php8.2-mysql php8.2-mbstring
        - php -v
        - sudo apt install libonig5
    - name: "PHP: 8.3"
      dist: jammy
      language: ruby
      addons:
        postgresql: "14"
      before_install:
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:ondrej/php
        - sudo apt update
        - sudo apt install php8.3 php8.3-pgsql php8.3-mysql php8.3-mbstring
        - php -v
        - sudo apt install libonig5
    - name: "PHP: 8.4"
      dist: jammy
      language: ruby
      addons:
        postgresql: "14"
      before_install:
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:ondrej/php
        - sudo apt update
        - sudo apt install php8.4 php8.4-pgsql php8.4-mysql php8.4-mbstring
        - php -v
        - sudo apt install libonig5
    - name: "PHP: 8.5"
      dist: jammy
      language: ruby
      addons:
        postgresql: "14"
      before_install:
        - sudo apt install software-properties-common
        - sudo add-apt-repository ppa:ondrej/php
        - sudo apt update
        - sudo apt install php8.5 php8.5-pgsql php8.5-mysql php8.5-mbstring
        - php -v
        - sudo apt install libonig5

before_script:
  - composer update --dev 2>&1
  - sudo mysql -u root -e "USE mysql; UPDATE user SET Grant_priv='Y' WHERE User='root';" # What? root does not have Grant privilege?
  - sudo mysql -u root -e "FLUSH PRIVILEGES;"
  - sudo mysql -u root -e "CREATE DATABASE test CHARACTER SET 'UTF8';"
  - sudo mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test'; GRANT ALL ON *.* TO 'test'@'localhost'";
  - sudo mysql -u root -e "FLUSH PRIVILEGES;"
  - sudo -u postgres psql -c "CREATE DATABASE test;" -U postgres
  - sudo -u postgres psql -c "CREATE USER test WITH ENCRYPTED PASSWORD 'test'; GRANT ALL PRIVILEGES ON DATABASE test TO test;" -U postgres

script:
  - cd test && ../vendor/bin/run_unit_tests
